#!/bin/bash
editor="nano"
files=$(git diff --cached --name-only --oneline)
changed=0

if [ -z "$files" ]
then
    echo "Nothing to commit."
    exit 0
fi

> .commitment
echo -e "# https://github.com/kaangiray26/commitment\n# Please type your commit messages.\n" >> .commitment

while IFS= read -r line; do
    echo "#$line " >> .commitment
done <<< "$files"

$editor .commitment

while IFS= read -r line; do
    if ! [[ $line == \#* ]]
    then
        arr=($line)
        if [[ ${#arr[@]} > 1 ]]
        then
            message=${arr[@]:1}
            message=${message//$'\t\r\n'/}
            
            git commit -m "$message" "${arr[0]}" --quiet
            changed=1
        fi
    fi
done < .commitment

if [[ changed -eq 1 ]]; then
    git push --quiet
fi
echo "done."
